### ISSUE TITLE
Add ability to use `CryptoKey` objects as identities

### ISSUE THREAD

**Issue by wiktor-k** [FiloSottile/typage#19]
Subtle Crypto allows handling non-extractable private keys via the [`CryptoKey` objects](https://developer.mozilla.org/en-US/docs/Web/API/CryptoKey). This, coupled with the [recent addition of X25519 to WebCrypto](https://github.com/tQsW/webcrypto-curve25519/blob/master/explainer.md#key-agreement-with-x25519) and a [growing number of browsers supporting it](https://wpt.fyi/results/WebCryptoAPI/generateKey/successes_X25519.https.any.html?label=master&label=experimental&aligned&view=subtest&q=x25519) would mean that it'd be possible to store X25519 identity keys in a non-extractable form in the browser.

I think it'd be a good addition to typage to support passing raw `CryptoKey` objects as identities.

(Another angle would be long-term migration to WebCrypto when the browser support is better. I've done a similar thing for [ssh signatures](https://github.com/wiktor-k/ssh-sig?tab=readme-ov-file#supported-algorithms)).

**Comment by FiloSottile** [comment]
Ah yes this is definitely something we should support.

Would it be reasonable to just autodetect WebCrypto support and use it in place of libsodium.js (or noble, see #20) even when the key is passed in raw? Looks like even Node and Deno support it these days, right?

What's the best way to test this and the fallback? Run the full suite in a browser? Rely on Node's and Deno's implementations? Artificially stump the auto-detection to test the fallback?

**Comment by FiloSottile** [comment]
Oof, except all WebCrypto APIs are async, so we'd have to change the public APIs to be async, right? Is there any convention for how to handle this?

**Comment by wiktor-k** [comment]
> Would it be reasonable to just autodetect WebCrypto support and use it in place of libsodium.js (or noble, see https://github.com/FiloSottile/typage/issues/20) even when the key is passed in raw? Looks like even Node and Deno support it these days, right?

I've discussed that with the X25519-in-WebCrypto draft author and from what I can gather the support in browsers is widespread and modulo some small details with the spec (making the construction more robust IIUC) it's going to be natively supported (finally! I might add).

> What's the best way to test this and the fallback? Run the full suite in a browser? Rely on Node's and Deno's implementations? Artificially stump the auto-detection to test the fallback?

That's a good question. I'd add end-to-end tests and run then in a variety of browsers. The check whether the fallback is used should be just informative, unless you're explicitly targetting non-evergreen browsers the "fallback is not necessary now" may be an indicator that the fallback code can be completely removed.

This is quite a bit of additional work - great that you're thinking it through.

> Oof, except all WebCrypto APIs are async, so we'd have to change the public APIs to be async, right? Is there any convention for how to handle this?

Ugh, right. Indeed they are async and async-ness would need to be propagated upwards up to the API. Technically it is possible to offer one API that can be used in sync and async fashion (see [this](https://curiosity-driven.org/promises-and-generators)) but this sounds like an additional complexity. The advantage of the async API is that it's more HSM-friendly (say, if the request is propagated to external service, or a Yubikey exposing site that asks for a PIN and then a touch, the async promise would wait until it's all done).

Thanks for your time! :wave:

**Comment by Valodim** [comment]
> Oof, except all WebCrypto APIs are async, so we'd have to change the public APIs to be async, right? Is there any convention for how to handle this?

I seem to be a day late to the party, but I'll add that using async everywhere is a bit of a bummer. Using async is a non-negligible cost for contexts which aren't already async. I can't speak for others, but the easiest way to work with this for my own use case is probably patching out the WebCrypto support in favor of a non-async API in our dependency.

Thinking of possible solutions, none that comes to mind seems particularly attractive. It's not possible here to use overloaded typings, since the `decrypt` method can't tell ahead of time what kind of key it'll use. Adding independent methods would break consistency with the typical age interface. And maintaining independent libraries for webcrypto/purejs APIs adds a lot of maintenance overhead.

**Comment by wiktor-k** [comment]
>I agree in principle, but in practice it depends on how annoying the "just to get a sync interface" part really is in a codebase. Going async is not free, and depending on what you do even requires additional locking to avoid race conditions.

This really boils down to the [function coloring problem](https://journal.stuffwithstuff.com/2015/02/01/what-color-is-your-function/) and is not specific to typage but rather a more general issue.

Technically it's possible to write code agnostic to sync/async [by using generators](https://curiosity-driven.org/promises-and-generators) but sometimes the cure is worse than the disease ;)

> Still, I agree it may well be the correct decision to stay async for typage here just for this reason. Annoying. 😒

I feel like the writing was on the wall and the sync interface, as nice as it was, was never going to stay forever. As I mentioned in the other comment, other high-level crypto libraries are already using async interface anyway. :man_shrugging:
